# Generated by Django 3.1.1 on 2020-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='isSavingAccount',
            field=models.BooleanField(default=True),
        ),
    ]
