# Generated by Django 3.0.5 on 2020-04-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('groupings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('_createdOn', models.DateTimeField(auto_now=True)),
                ('maxTransactions', models.IntegerField()),
                ('current', models.IntegerField(default=0)),
                ('filterCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupings.Category')),
                ('transactions', models.ManyToManyField(to='transactions.Expense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('_createdOn', models.DateTimeField(auto_now=True)),
                ('maxAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('filterCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupings.Category')),
                ('transactions', models.ManyToManyField(to='transactions.Expense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
