# Generated by Django 3.0.5 on 2020-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200428_2138'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencybudget',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='transactions.Expense'),
        ),
        migrations.AlterField(
            model_name='transactionbudget',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='transactions.Expense'),
        ),
    ]
