# Generated by Django 3.0.5 on 2020-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('active', models.BooleanField(default=True)),
                ('_createdOn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
