# Generated by Django 3.1.1 on 2020-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_issavingsaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='isSavingsAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='isSavingAccount',
            field=models.BooleanField(default=False),
        ),
    ]
