# Generated by Django 3.0.5 on 2020-04-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('groupings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('spendOn', models.DateField(auto_now_add=True)),
                ('_createdOn', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='income', editable=False, max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groupings.Category')),
                ('tags', models.ManyToManyField(blank=True, to='groupings.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('spendOn', models.DateField(auto_now_add=True)),
                ('_createdOn', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='expense', editable=False, max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groupings.Category')),
                ('tags', models.ManyToManyField(blank=True, to='groupings.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
