# Generated by Django 3.0.5 on 2020-04-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupings.Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='groupings.Tag'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupings.Category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='groupings.Tag'),
        ),
    ]
