
// Account action types

export const FETCH_ALL_ACCOUNTS_PENDING = 'FETCH_ALL_ACCOUNTS_PENDING'
export const FETCH_ALL_ACCOUNTS_SUCCESS = 'FETCH_ALL_ACCOUNTS_SUCCESS'
export const FETCH_ALL_ACCOUNTS_ERROR = 'FETCH_ALL_ACCOUNTS_ERROR'
