
// Account action types

export const FETCH_ALL_ACCOUNTS_PENDING = 'FETCH_ALL_ACCOUNTS_PENDING'
export const FETCH_ALL_ACCOUNTS_SUCCESS = 'FETCH_ALL_ACCOUNTS_SUCCESS'
export const FETCH_ALL_ACCOUNTS_ERROR = 'FETCH_ALL_ACCOUNTS_ERROR'

// Budget action types
export const FETCH_ALL_BUDGETS_PENDING = 'FETCH_ALL_BUDGETS_PENDING'
export const FETCH_ALL_BUDGETS_SUCCESS = 'FETCH_ALL_BUDGETS_SUCCESS'
export const FETCH_ALL_BUDGETS_ERROR = 'FETCH_ALL_BUDGETS_ERROR'

// Transaction action types
export const FETCH_ALL_TRANSACTIONS_PENDING = 'FETCH_ALL_TRANSACTIONS_PENDING'
export const FETCH_ALL_TRANSACTIONS_SUCCESS = 'FETCH_ALL_TRANSACTIONS_SUCCESS'
export const FETCH_ALL_TRANSACTIONS_ERROR = 'FETCH_ALL_TRANSACTIONS_ERROR'
