
// Account action types

export const FETCH_ALL_ACCOUNTS_PENDING = 'FETCH_ALL_ACCOUNTS_PENDING'
export const FETCH_ALL_ACCOUNTS_SUCCESS = 'FETCH_ALL_ACCOUNTS_SUCCESS'
export const FETCH_ALL_ACCOUNTS_ERROR = 'FETCH_ALL_ACCOUNTS_ERROR'

// Budget action types
export const FETCH_ALL_BUDGETS_PENDING = 'FETCH_ALL_BUDGETS_PENDING'
export const FETCH_ALL_BUDGETS_SUCCESS = 'FETCH_ALL_BUDGETS_SUCCESS'
export const FETCH_ALL_BUDGETS_ERROR = 'FETCH_ALL_BUDGETS_ERROR'

// Transaction action types
export const FETCH_ALL_TRANSACTIONS_PENDING = 'FETCH_ALL_TRANSACTIONS_PENDING'
export const FETCH_ALL_TRANSACTIONS_SUCCESS = 'FETCH_ALL_TRANSACTIONS_SUCCESS'
export const FETCH_ALL_TRANSACTIONS_ERROR = 'FETCH_ALL_TRANSACTIONS_ERROR'

export const UPDATE_EXPENSE_PENDING = 'UPDATE_EXPENSE_PENDING'
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS'
export const UPDATE_EXPENSE_ERROR = 'UPDATE_EXPENSE_ERROR'

export const UPDATE_INCOME_PENDING = 'UPDATE_INCOME_PENDING'
export const UPDATE_INCOME_SUCCESS = 'UPDATE_INCOME_SUCCESS'
export const UPDATE_INCOME_ERROR = 'UPDATE_INCOME_ERROR'

// Category action types
export const FETCH_ALL_CATEGORIES_PENDING = 'FETCH_ALL_CATEGORIES_PENDING'
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS'
export const FETCH_ALL_CATEGORIES_ERROR = 'FETCH_ALL_CATEGORIES_ERROR'

// Category action types
export const FETCH_ALL_TAGS_PENDING = 'FETCH_ALL_TAGS_PENDING'
export const FETCH_ALL_TAGS_SUCCESS = 'FETCH_ALL_TAGS_SUCCESS'
export const FETCH_ALL_TAGS_ERROR = 'FETCH_ALL_TAGS_ERROR'
